remove set -e

diff --git a/scripts/01-setup b/scripts/01-setup
--- a/scripts/01-setup
+++ b/scripts/01-setup
@@ -1,5 +1,7 @@
 #! /bin/bash
-set -e
+
+# Do not set -e because it's easier if most commands still run even when one fails
+#set -e
 
 cd ~
 if [[ $SHELL == *"zsh"* ]]; then
